import { ReactNode } from "react";
import type { Metadata } from "next";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import "./globals.css";

type RootLayoutProps = Readonly<{ children: ReactNode }>;

export const metadata: Metadata = {
  title: "Nest.js 14 - Demo",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className="antialiased bg-gray-900 text-gray-100">
        <div className="max-w-7xl mx-auto p-4 sm:p-6 lg:p-8">
          <Navigation />
          <main className="py-8">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
